folder_main_path = "C:\\Users\\Admin\\Desktop\\Camerin\\backend\\uploads\\modules"
project_name = "\\dbCompare\\QuickRatioComparisonBetweenSourceColumns"
group_name_left = "\\Left"
group_name_right = "\\Right"
folder_input_name_module = "\\Inputs\\"
folder_output_name_module = "\\Outputs"
group_name_for_filename_left = "Left_Entity"
group_name_for_filename_right = "Right_Entity"
folder_input_name_module_for_filename = ".Source_Dump"
folder_output_name_module_for_filename = "Quick_ratio_Column_Names_Compare."
output_file_extn = ".xlsx"
sheet_name = "Quick_ratio_Names_Compare"
#exec(open(r'C:\Python_Code\QuickRatio_Comparison_between_Source_Columns_v2.py').read(), globals())
